export * from  './login/login.component';
export * from './register/register.component';
export * from './home/home.component';
export * from './hotel-list/hotel-list.component';
export * from './booking/booking.component';
export * from './booking-history/booking-history.component';
export * from './summery/summery.component';
export * from './review/review.component';
export * from './review-list/review-list.component';